
#Appium Configuration
appium.server.url=http://127.0.0.1:4723/

#Device Capabilities
platform.name =Android
automation.name=uiautomator2
platform.version=15.0
device.name=Medium Tablet API 35

#App Configuration
app.path=/src/main/java/com.survey/FieldApps/app-debug.apk
app.package=com.gevernova.ent.gridos.fieldapp
app.activity=com.gevernova.ent.gridos.fieldapp.MainActivity

#Timrouts (in seconds)
timeout.implicit=10
timeout.explicit=30
timeout.page.load=60
timeout.app.load=300
timeout.new.command=600
timeout.uiautomator2.launch=60000
timeout.uiautomator2.install=60000

#Appium Special Capabilities
snapshot.max.dept=60
custom.snapshot.timeout=5000
chromedriver.autodownload=true
full.reset=true

#Environment
defult.environment=4
